# Generated by Django 3.2.7 on 2022-05-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1_quantity', models.CharField(max_length=50)),
                ('item2_quantity', models.CharField(max_length=50)),
                ('item3_quantity', models.CharField(max_length=50)),
                ('item4_quantity', models.CharField(max_length=50)),
            ],
        ),
    ]
