# Generated by Django 3.2.7 on 2022-05-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='bill',
        ),
    ]
