# Generated by Django 3.2.7 on 2022-05-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_list_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='item2_quantity',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='item3_quantity',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='item4_quantity',
        ),
        migrations.AddField(
            model_name='bill',
            name='s_no',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='s_no',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
