# Generated by Django 3.2.7 on 2022-05-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220514_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_quantity', models.CharField(max_length=50)),
                ('item_price', models.CharField(max_length=50)),
            ],
        ),
    ]
