# Generated by Django 3.2.7 on 2022-05-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='item_total',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
